// <auto-generated />
using JuliaSmerdelEFCompanies;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuliaSmerdelEFCompanies.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20230408133636_CompaniesSecond")]
    partial class CompaniesSecond
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("JuliaSmerdelEFCompanies.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyID");

                    b.ToTable("Companies");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("JuliaSmerdelEFCompanies.Customer", b =>
                {
                    b.HasBaseType("JuliaSmerdelEFCompanies.Company");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Discount")
                        .HasColumnType("INTEGER");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("JuliaSmerdelEFCompanies.Supplier", b =>
                {
                    b.HasBaseType("JuliaSmerdelEFCompanies.Company");

                    b.Property<int>("SupplierID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("bankAccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("JuliaSmerdelEFCompanies.Customer", b =>
                {
                    b.HasOne("JuliaSmerdelEFCompanies.Company", null)
                        .WithOne()
                        .HasForeignKey("JuliaSmerdelEFCompanies.Customer", "CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JuliaSmerdelEFCompanies.Supplier", b =>
                {
                    b.HasOne("JuliaSmerdelEFCompanies.Company", null)
                        .WithOne()
                        .HasForeignKey("JuliaSmerdelEFCompanies.Supplier", "CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
