// <auto-generated />
using JuliaSmerdelEFProducts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuliaSmerdelEFProducts.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20230408061224_FifthModification")]
    partial class FifthModification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("JuliaSmerdelEFProducts.Invoice", b =>
                {
                    b.Property<int>("InvoiceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("InvoiceNumber");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("JuliaSmerdelEFProducts.InvoiceInfo", b =>
                {
                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvoiceNumber", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("InvoiceInfos");
                });

            modelBuilder.Entity("JuliaSmerdelEFProducts.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitsOnStock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("JuliaSmerdelEFProducts.InvoiceInfo", b =>
                {
                    b.HasOne("JuliaSmerdelEFProducts.Invoice", "Invoice")
                        .WithMany("InvoiceInfos")
                        .HasForeignKey("InvoiceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuliaSmerdelEFProducts.Product", "Product")
                        .WithMany("InvoiceInfos")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JuliaSmerdelEFProducts.Invoice", b =>
                {
                    b.Navigation("InvoiceInfos");
                });

            modelBuilder.Entity("JuliaSmerdelEFProducts.Product", b =>
                {
                    b.Navigation("InvoiceInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
